1) Given the array split the array at the middle (if it is odd length consider next higher integer), add reverse the array.

Ex:
if input is [12,10,5,6,52,36] 
output should be [6,52,36,12,10,5]

if input is  [12,10,5,6,52,36,34]
output should be [6,52,36,34,12,10,5]

In [1]:
import math
# Complete this function to get the desired result
def reverseatCenter(arr):
    split_index = len(arr)//2
    arr2 = arr[split_index:] + arr[:split_index]
    return arr2

In [2]:
# Print working examples for Question 1
input_arrays = [[12,10,5,6,52,36],
                [12,10,5,6,52,36,34],
                [1,2],
                [78],
                [500, 890, 789]]

for i, arr in enumerate(input_arrays):
    print("Example {}".format(i + 1))
    print("Input:", *arr)
    print("Output:", *reverseatCenter(arr), "\n")

Example 1
Input: 12 10 5 6 52 36
Output: 6 52 36 12 10 5 

Example 2
Input: 12 10 5 6 52 36 34
Output: 6 52 36 34 12 10 5 

Example 3
Input: 1 2
Output: 2 1 

Example 4
Input: 78
Output: 78 

Example 5
Input: 500 890 789
Output: 890 789 500 



2) Given a list of numbers, return a list where all adjacent duplicate elements have been removed.

Ex:

2, 2, 2, 3, 2 returns 2, 3, 2.

In [3]:
# Complete the function to get the desired result
def remove_adjacent(b):
    n = len(b)
    ind = 1
    prev = b[0]
    while n > 1:
        if b[ind]==prev:
            b.pop(ind)
        else:
            prev = b[ind]
            ind = ind + 1
        n = n - 1
    return b

In [4]:
# Print working examples for Question 2
input_arrays = [[2, 2, 2, 3, 2],
                [1, 1, 2, 2, 3, 4, 4, 4, 4, 5, 6, 7],
                [-9, -9, 89, 89],
                [78, 78, 78, 78, 78],
                [500, 890, 789, 890, 890, 500, 1, 2, 2]]

for i, arr in enumerate(input_arrays):
    print("Example {}".format(i + 1))
    print("Input:", *arr)
    print("Output:", *remove_adjacent(arr), "\n")

Example 1
Input: 2 2 2 3 2
Output: 2 3 2 

Example 2
Input: 1 1 2 2 3 4 4 4 4 5 6 7
Output: 1 2 3 4 5 6 7 

Example 3
Input: -9 -9 89 89
Output: -9 89 

Example 4
Input: 78 78 78 78 78
Output: 78 

Example 5
Input: 500 890 789 890 890 500 1 2 2
Output: 500 890 789 890 500 1 2 



3) given matrix of 7x7 full of ones, create a square with given side length (center same as original square(7x7)) replace ones with zeors at the edges for example,



$$
\begin{align}
A = \begin{bmatrix}
1 & 1 & 1 & 1 & 1 & 1 & 1\\
1 & 1 & 1 & 1 & 1 & 1 & 1\\
1 & 1 & 1 & 1 & 1 & 1 & 1\\
1 & 1 & 1 & 1 & 1 & 1 & 1\\
1 & 1 & 1 & 1 & 1 & 1 & 1\\
1 & 1 & 1 & 1 & 1 & 1 & 1\\
1 & 1 & 1 & 1 & 1 & 1 & 1\\
\end{bmatrix}
\end{align}
$$
After modification
$$
\begin{align}
A = \begin{bmatrix}
1 & 1 & 1 & 1 & 1 & 1 & 1\\
1 & 1 & 1 & 1 & 1 & 1 & 1\\
1 & 1 & 0 & 0 & 0 & 1 & 1\\
1 & 1 & 0 & 1 & 0 & 1 & 1\\
1 & 1 & 0 & 0 & 0 & 1 & 1\\
1 & 1 & 1 & 1 & 1 & 1 & 1\\
1 & 1 & 1 & 1 & 1 & 1 & 1\\
\end{bmatrix}
\end{align}
$$

In [5]:
import numpy as np
def modify_matrix(A, k):
    mid_ind = A.shape[0]//2
    offset = (k - 1)//2
    horizontal_side = np.zeros(k, dtype=int)
    vertical_side = np.zeros((1, k), dtype=int)
    A[mid_ind - offset:mid_ind + offset + 1, mid_ind-offset] = vertical_side
    A[mid_ind - offset:mid_ind + offset + 1, mid_ind+offset] = vertical_side
    A[mid_ind-offset, mid_ind - offset:mid_ind + offset + 1] = horizontal_side
    A[mid_ind+offset, mid_ind - offset:mid_ind + offset + 1] = horizontal_side
    return A

In [6]:
#Print working examples
A = np.ones((7, 7), dtype=int)
# Display the original 7 x 7 matrix of ones
print("Original matrix:")
print(A)

# Print the modified matrix for k = 1, 3, 5, 7 (k has to be odd, as the centres of both squares have to coincide)
k_values = [1, 3, 5, 7]
for k in k_values:
    print("For k = {}".format(k))
    A = np.ones((7, 7), dtype=int)
    print(modify_matrix(A, k))
    print()

Original matrix:
[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]
For k = 1
[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 0 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]

For k = 3
[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 0 0 0 1 1]
 [1 1 0 1 0 1 1]
 [1 1 0 0 0 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]

For k = 5
[[1 1 1 1 1 1 1]
 [1 0 0 0 0 0 1]
 [1 0 1 1 1 0 1]
 [1 0 1 1 1 0 1]
 [1 0 1 1 1 0 1]
 [1 0 0 0 0 0 1]
 [1 1 1 1 1 1 1]]

For k = 7
[[0 0 0 0 0 0 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 0 0 0 0 0 0]]



4) Paragraph present in data.txt is encoded such that each alphabet in word is incremented to next ascii value. Decode the paragraph present in the data_encoded.txt (Hint: decrease the ascii value of each character in the word)


In [7]:
def sentence_decode(str):
    s = str
    dec_char_list = [chr(ord(char) - 1) if char != ' ' else char for char in s]
    dec_words = ''.join(dec_char_list)
    return dec_words

In [8]:
with open ("data_encoded.txt", "r") as myfile:
    data=myfile.read()
    print(data)
    print(" ")
    print(sentence_decode(data))

ebub bobmztjt jt b qspdftt pg jotqfdujoh- dmfbotjoh- usbotgpsnjoh boe npefmjoh ebub xjui uif hpbm pg ejtdpwfsjoh vtfgvm jogpsnbujpo- jogpsnjoh dpodmvtjpot boe tvqqpsujoh efdjtjpo.nbljoh/ ebub bobmztjt ibt nvmujqmf gbdfut boe bqqspbdift- fodpnqbttjoh ejwfstf ufdiojrvft voefs b wbsjfuz pg obnft- boe jt vtfe jo ejggfsfou cvtjoftt- tdjfodf- boe tpdjbm tdjfodf epnbjot/ jo upebz(t cvtjoftt xpsme- ebub bobmztjt qmbzt b spmf jo nbljoh efdjtjpot npsf tdjfoujgjd boe ifmqjoh cvtjofttft pqfsbuf npsf fggfdujwfmz/
 
data analysis is a process of inspecting, cleansing, transforming and modeling data with the goal of discovering useful information, informing conclusions and supporting decision-making. data analysis has multiple facets and approaches, encompassing diverse techniques under a variety of names, and is used in different business, science, and social science domains. in today's business world, data analysis plays a role in making decisions more scientific and helping businesses operate more

In [9]:
# Has to print the decoded paragraph.